export const content = {
  brand: {
    name: "Creation Pro",
    slogan: "SYSTEMS. NOT SUGGESTIONS.",
    tagline: "Operação para projetos que importam.",
    microcopy: "Clareza. Ritmo. Execução.",
    footerTagline: "Arquitetura Operacional para Projetos Complexos.",
    locations: "Brasil | Estados Unidos | Espanha",
  },
  nav: {
    home: "Início",
    about: "Quem Somos",
    services: "Serviços",
    method: "Método",
    productions: "Produções",
    impact: "Impacto",
    contact: "Contato",
    cta: "Agendar uma Conversa",
  },
  hero: {
    headline: "Operações, produções e impacto para fazer acontecer.",
    subheadline: "Organizamos processos, equipes e governança para que projetos de impacto, cultura, inovação e expansão finalmente funcionem.",
    cta: "Agende uma conversa",
    secondary: "Conhecer o Método",
  },
  whatWeDo: {
    title: "O que fazemos",
    description: "Criamos estrutura, clareza e ritmo em iniciativas complexas.",
    subtext: "Onde há múltiplos stakeholders, sobrecarga e entregas travadas, nós construímos a operação necessária para fazer acontecer.",
  },
  creationOps: {
    badge: "Nosso Método",
    title: "Creation OPS",
    subtitle: "90 dias para organizar e operacionalizar projetos complexos",
    description: "O programa que resolve a raiz do caos operacional. Não oferecemos diagnósticos teóricos — instalamos a operação que seu projeto precisa.",
    phases: [
      {
        number: "01",
        title: "Diagnóstico Operacional",
        duration: "Fase 1",
        description: "Mapeamos fluxos, gargalos, papéis e dependências. Entregamos clareza imediata sobre o que está travando.",
        deliverables: ["Mapeamento completo da operação", "Leitura de rotina", "Identificação de gargalos", "Papéis e responsabilidades", "Plano de correção imediato"],
      },
      {
        number: "02",
        title: "Estruturação",
        duration: "Fase 2",
        description: "Criamos processos, rotinas, rituais, governança e papéis. Construímos a operação que o projeto precisa.",
        deliverables: ["Processos claros", "Governança e rituais", "Agenda e cadência", "Documentação", "Fluxos executáveis"],
      },
      {
        number: "03",
        title: "Execução Acompanhada",
        duration: "Fase 3",
        description: "Acompanhamos a operação até rodar — garantindo ritmo, alinhamento e sustentabilidade.",
        deliverables: ["Acompanhamento próximo", "Correções em tempo real", "Ajuste de ritmo", "Suporte à liderança", "Entrega com sustentabilidade"],
      },
    ],
    result: "No final, você terá uma operação clara, documentada e replicável — que funciona mesmo quando você não está presente.",
    cta: "Quero saber mais",
  },
  targetAudience: {
    title: "Para quem trabalhamos",
    subtitle: "Trabalhamos com organizações que precisam de estrutura para fazer projetos importantes acontecerem.",
    audiences: [
      {
        title: "ONGs, Fundações e Institutos",
        description: "Estruturamos operações para que projetos com propósito ganhem força, consistência e impacto real.",
        tag: "OPS Impact",
      },
      {
        title: "Hubs, Labs, Cultura e Educação",
        description: "Ambientes criativos precisam de ordem para gerar resultados. Nós tornamos essas operações funcionais.",
        tag: "OPS Creative",
      },
      {
        title: "Food, Retail e Negócios Físicos em Expansão",
        description: "Expansão só existe com modelo replicável. Nós criamos esse modelo.",
        tag: "OPS Expansion",
      },
      {
        title: "Inovação, ESG e áreas internas sobrecarregadas",
        description: "Transformamos iniciativas internas em operações contínuas e claras.",
        tag: "Interno",
      },
    ],
  },
  whyWeExist: {
    title: "Por que existimos",
    text: "A maioria dos projetos falha na execução, não na ideia. Nós criamos a estrutura necessária para que iniciativas importantes — sociais, culturais, educacionais ou de expansão — saiam do papel e se sustentem.",
  },
  about: {
    title: "Quem Somos",
    intro: "A Creation Pro é um estúdio estratégico especializado em Arquitetura Operacional. Entramos em projetos complexos para organizar, estruturar e criar a operação necessária para executar com clareza, ritmo e sustentabilidade.",
    subIntro: "Trabalhamos onde existe caos: múltiplos stakeholders, equipes sobrecarregadas, decisões difusas e processos inexistentes. Nossa função é criar ordem.",
    mission: {
      title: "Missão",
      text: "Criar a estrutura, os processos e a governança que permitem que projetos de impacto, inovação e expansão realmente funcionem.",
    },
    vision: {
      title: "Visão",
      text: "Ser referência global em operação estratégica aplicada a impacto, expansão e inovação, atuando no Brasil, Estados Unidos e Europa até 2030.",
    },
    values: {
      title: "Valores",
      items: [
        { title: "Clareza Radical", description: "Se não está claro, não funciona." },
        { title: "Execução com Propósito", description: "Projetos importantes merecem operações fortes." },
        { title: "Estrutura Antes da Velocidade", description: "Nenhuma iniciativa prospera em cima de caos." },
        { title: "Coerência Humana", description: "Processos precisam servir as pessoas — não o contrário." },
        { title: "Praticidade Irrefutável", description: "Nada só no papel. Tudo precisa funcionar na prática." },
        { title: "Replicabilidade Sustentável", description: "Projetos podem ser únicos; modelos precisam ser consistentes." },
      ],
    },
    whatWeDo: {
      title: "O que fazemos",
      text: "Organizamos projetos complexos, criamos processos, estruturamos equipes, implementamos governança e acompanhamos a execução até funcionar.",
    },
    whatWeDontDo: {
      title: "O que não fazemos",
      items: [
        "Não somos agência",
        "Não somos produtora",
        "Não somos PMO burocrático",
        "Não somos consultoria tradicional",
        "Não operamos atividades rotineiras do cliente",
      ],
      conclusion: "Somos: Arquitetos Operacionais. Criamos a estrutura que permite que tudo aconteça.",
    },
  },
  services: {
    title: "Nossas Soluções Operacionais",
    subtitle: "Soluções focadas em fazer projetos complexos funcionarem",
    mainService: {
      title: "Creation OPS",
      badge: "Programa Principal",
      subtitle: "90 dias para organizar e operacionalizar projetos complexos",
      description: "O programa que resolve a raiz do caos operacional.",
    },
    subServices: [
      {
        title: "OPS Impact",
        subtitle: "ONGs, Fundações e Institutos",
        problem: "Estruturamos operações sociais para que projetos importantes não morram por falta de processo. Transformamos intenção em execução.",
        delivery: "Solução para falta de governança, sobrecarga, ausência de processos, projetos travados, múltiplos stakeholders e falta de clareza.",
        audience: "Organizações de impacto que precisam sair do modo 'apagar incêndio' e entrar no modo 'operação profissional'.",
        result: "Uma operação que gera resultados mensuráveis e não depende de heróis individuais.",
      },
      {
        title: "OPS Creative",
        subtitle: "Cultura, Educação, Hubs e Labs",
        problem: "Ambientes criativos precisam de ordem para gerar impacto real.",
        delivery: "Processos simples, estrutura operacional, coordenação entre áreas, rituais de alinhamento, ritmo e cadência.",
        audience: "Ambientes criativos que precisam de organização mas têm medo de perder a essência.",
        result: "Estrutura que liberta ao invés de aprisionar — mais tempo para criar, menos tempo apagando incêndio.",
      },
      {
        title: "OPS Expansion",
        subtitle: "Food, Retail e Negócios Físicos",
        problem: "Expansão exige modelo. Nós criamos esse modelo.",
        delivery: "Padronização, processos replicáveis, operação base, governança para expansão, acompanhamento.",
        audience: "Negócios físicos em expansão que precisam de consistência para crescer sem perder qualidade.",
        result: "Operação padronizada, replicável e escalável — cada unidade funcionando no mesmo padrão.",
      },
    ],
  },
  method: {
    title: "O Método Creation OPS",
    subtitle: "Um framework de 90 dias para organizar e operacionalizar qualquer projeto complexo.",
    phases: [
      {
        title: "1. Diagnóstico Operacional",
        description: "Clareza total sobre o que trava a operação.",
      },
      {
        title: "2. Estruturação",
        description: "Processos, governança, papéis, rituais e fluxos.",
      },
      {
        title: "3. Execução Acompanhada",
        description: "Acompanhamos até a operação rodar com consistência.",
      },
    ],
    howWeWork: {
      title: "Como trabalhamos",
      items: [
        "Reuniões semanais",
        "Entregas semanais",
        "Comunicação clara",
        "Documentação acessível",
        "Adaptação ao contexto",
        "Zero ruído",
        "Sem burocracia",
        "Foco total na prática",
      ],
    },
  },
  contact: {
    title: "Vamos estruturar a operação do seu projeto?",
    subtitle: "Agende uma conversa de diagnóstico",
    description: "Se sua iniciativa está travada, complexa, confusa ou sobrecarregada — nós podemos ajudar. A Creation Pro estrutura processos, equipes e governança para que sua operação funcione de forma clara, humana e sustentável.",
    form: {
      name: "Seu nome",
      namePlaceholder: "Marina Jesus",
      email: "Seu e-mail",
      emailPlaceholder: "marina@instituicao.com.br",
      organization: "Nome da organização",
      projectType: "Tipo de projeto",
      projectTypes: [
        "ONG / Fundação / Instituto",
        "Hub / Lab / Cultura / Educação",
        "Food / Retail / Negócio em expansão",
        "Equipe interna de empresa",
        "Outro",
      ],
      message: "Conte brevemente sobre seu projeto",
      submit: "Agendar conversa",
      sending: "Enviando...",
    },
    alternatives: {
      title: "Ou se preferir",
      email: "info@creation-pro.com",
      phone: "+55 21 999176231",
      whatsapp: "Chamar no WhatsApp",
    },
  },
  footer: {
    description: "Arquitetura Operacional para Projetos Complexos.",
    locations: "Brasil | Estados Unidos | Espanha",
    links: {
      company: {
        title: "A Creation",
        items: ["Quem Somos", "Soluções", "Método", "Contato"],
      },
      services: {
        title: "Soluções",
        items: ["Creation OPS", "OPS Impact", "OPS Expansion", "OPS Creative"],
      },
    },
    cta: "Agendar Conversa",
    copyright: "Creation Pro. Todos os direitos reservados.",
  },
};
